FROM python:3.12-slim

WORKDIR /app

# Встановлюємо залежності
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Налаштовуємо PYTHONPATH, щоб імпорти працювали правильно
ENV PYTHONPATH=/app

EXPOSE 8000

# Запускаємо FastAPI (reload не потрібен в Docker, але можна додати)
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]